var = input("Type anything: ")
print("The type of this value is ", type(var))
print("Is there only space? ", var.isspace())
print("Is it a number? ", var.isnumeric())
print("Is it alphabetical? ", var.isalpha())
print("Is it alphanumeric? ", var.isalnum())
print("Is it upper? ", var.isupper())
print("Is it lower? ", var.islower())
print("Is it capitalized? ", var.istitle())
